export default {
  title: `Công thức các loại cà phê pha máy`,
  tags: ['barista'],
  spoiler: "CAPPUCCINO, LATTE, ICED CAPPUCCINO, ICED LATTE, ICED CAFÉ MOCHA, ICED CARAMEL MACCHIATO, ITALIAN SODA – BLUE OCEAN SODA, ITALIAN SODA – ROMANCE  SODA, MOJITO MOCKTAIL, SMOOTHIES CHILLER, YOGURT SMOOTHIES, CHOCOLATE ICED BLENDED, CHOCOLATE MINT ICED BLENDED, MATCHA ICED BLENDED, COFFEE ICED BLENDED, COOK ICED BLENDED, TRÀ ĐÀO CAM SẢ",
  getContent: () => import('./document.mdx'),
}