export default {
  title: `Popular cocktails`,
  tags: ['bartender'],
  spoiler: "LONG ISLAND ICED TEA, PINK LADY, WHISKY SOUR, OLD FASHIONED, GOD FATHER, MANHATTAN COCKTAIL, SIDE CAR, STINGER, BRANDY EGG NOG, COSMOPOLITAN, BLOODY MARY, SINGAPORE SLING, MOSSCOW MULE, CLASSIC DRY MARTINI, CAPIRINHA, CUBA LIBRE, MOJTO COCKTAIL, MARGARITA, TEQUILA SUNRISE, PINACOLADA, B52, P/S I LOVE U, JAPANESE SLIPPER, GRASSHOPPER",
  getContent: () => import('./document.mdx'),
}